name: Deploy

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: mvn clean install -B --file pom.xml
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "zoohotel" #Must be unique in Heroku
          heroku_email: "zooohotel@yandex.ru"
          usedocker: true  
        env:
          HD_VK_APP_ID : ${{ secrets.VK_APP_ID }}
          HD_VK_CLIENT_ID : ${{ secrets.VK_CLIENT_ID }}
          HD_VK_SERVICE_TOKEN : ${{ secrets.VK_SERVICE_TOKEN }}
          HD_YANDEX_MAP_API_KEY : ${{ secrets.YANDEX_MAP_API_KEY }}
