name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: mvn -B -DskipTests=true -Dspring.profiles.active=prod clean install --file pom.xml
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: zoohotel1
          heroku_email: "shamaneeel881@gmail.com"
          healthcheck: "https://zoohotel1.herokuapp.com/health"
          justlogin: true
          stack: heroku-20

      - name: "Login to heroku registry"
        run: heroku container:login

      - name: "Releases the container"
        run: heroku container:release web --app zoohotel1
        env:
          HD_VK_APP_ID : ${{ secrets.VK_APP_ID }}
          HD_VK_CLIENT_ID : ${{ secrets.VK_CLIENT_ID }}
          HD_VK_SERVICE_TOKEN : ${{ secrets.VK_SERVICE_TOKEN }}
          HD_YANDEX_MAP_API_KEY : ${{ secrets.YANDEX_MAP_API_KEY }}
          HD_EMAIL_LOGIN : ${{ secrets.VK_APP_ID }}
          HD_EMAIL_PASSWORD : ${{ secrets.VK_CLIENT_ID }}
          HD_SMSC_LOGIN : ${{ secrets.VK_SERVICE_TOKEN }}
          HD_SMSC_PASSWORD : ${{ secrets.YANDEX_MAP_API_KEY }}
          HD_KEYSTORE_LOCATION : ${{ secrets.KEYSTORE_LOCATION }}
          HD_KEYSTORE_PASSWORD : ${{ secrets.KEYSTORE_PASSWORD }}
          HD_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          HD_PRIVATE_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
          HD_PROD_POSTGRE_PASSWORD: ${{ secrets.PROD_POSTGRE_PASSWORD }}
          HD_PROD_POSTGRE_USERNAME: ${{ secrets.PROD_POSTGRE_USERNAME }}
          HD_PROD_POSTGRE_URL: ${{ secrets.PROD_POSTGRE_URL }}
