# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env: 
        VK_APP_ID : 7591749
        VK_CLIENT_ID : oxxDZtLfco5lVlbdXTkg
        VK_SERVICE_TOKEN : 0f890a330f890a330f890a33720ffadd7600f890f890a3350d03e8b7f506dc4b35201a3
        YANDEX_MAP_API_KEY : 6fdff1ef-9fc7-424b-9322-5147e58b2e00
